Climber class and extend, retract commands
Creekside-Robotics/Creekside-Robotics-2024-Season pull request #2
Opened 2024-02-19 17:35 UTC by AndreyGL0290

Briefly calculated conversion rate might be wrong.

2024-02-19 20:54 UTC, josephhadad05 requested changes
For the most part good. 

Small change requested. 

Also add a command that retracts the arms until they stop (hit the hard limit). Would need to use encoder velocity (not sure if there is a method for that but can be derived from position).

2024-02-19 20:54 UTC, josephhadad05 commented on src/main/java/frc/robot/subsystems/Climber.java
> +        else return 0;
should return zero if position is <=0. Otherwise, the position is zero for the full length of travel.

2024-02-19 20:54 UTC, josephhadad05 commented
Also, ignore the build failed. There is nothing wrong with your code, I'll get that fixed asap.

2024-02-20 07:30 UTC, AndreyGL0290 commented on src/main/java/frc/robot/subsystems/Climber.java
> +        else return position;
Fixed

> Should return zero if position is <=0. Otherwise, the position is zero for the full length of travel.

2024-02-21 02:35 UTC, josephhadad05 requested changes

2024-02-21 02:35 UTC, josephhadad05 commented on src/main/java/frc/robot/subsystems/Climber.java
> +        encoder.setVelocityConversionFactor(ClimberConstants.positionConversionRate/this.encoder.getMeasurementPeriod());
Velocity is by default, rotations per minute. 

Should be `ClimberConstants.postionConversionFactor / 60.0` to convert to meters per second.

2024-02-21 12:03 UTC, josephhadad05 commented
I don't think you need the measurement period as it is already handled. But just merge for now. We can see when we test.

2024-02-21 13:30 UTC, josephhadad05 approved these changes

2024-02-23 20:59 UTC, merged